In [147]:
import pandas as pd

In [148]:
player2_dict = {'ODI # 3796': {'Runs': 'DNB', 'Mins': '-', 'BF': '-', '4s': '-', '6s': '-', 'SR': '-', 'Pos': '-', 'Dismissal': '-', 'Inns': '2', 'Opposition': 'v New Zealand', 'Ground': 'Dharamsala', 'Start Date': '16 Oct 2016'}, 'ODI # 3797': {'Runs': '36', 'Mins': '51', 'BF': '32', '4s': '3', '6s': '0', 'SR': '112.50', 'Pos': '8', 'Dismissal': 'caught', 'Inns': '2', 'Opposition': 'v New Zealand', 'Ground': 'Delhi', 'Start Date': '20 Oct 2016'}, 'ODI # 3798': {'Runs': 'DNB', 'Mins': '-', 'BF': '-', '4s': '-', '6s': '-', 'SR': '-', 'Pos': '-', 'Dismissal': '-', 'Inns': '2', 'Opposition': 'v New Zealand', 'Ground': 'Mohali', 'Start Date': '23 Oct 2016'}, 'ODI # 3799': {'Runs': '9', 'Mins': '18', 'BF': '13', '4s': '0', '6s': '0', 'SR': '69.23', 'Pos': '8', 'Dismissal': 'caught', 'Inns': '2', 'Opposition': 'v New Zealand', 'Ground': 'Ranchi', 'Start Date': '26 Oct 2016'}, 'ODI # 3819': {'Runs': '40*', 'Mins': '60', 'BF': '37', '4s': '3', '6s': '1', 'SR': '108.10', 'Pos': '7', 'Dismissal': 'not out', 'Inns': '2', 'Opposition': 'v England', 'Ground': 'Pune', 'Start Date': '15 Jan 2017'}, 'ODI # 3821': {'Runs': '19*', 'Mins': '23', 'BF': '9', '4s': '2', '6s': '1', 'SR': '211.11', 'Pos': '7', 'Dismissal': 'not out', 'Inns': '1', 'Opposition': 'v England', 'Ground': 'Cuttack', 'Start Date': '19 Jan 2017'}, 'ODI # 3824': {'Runs': '56', 'Mins': '67', 'BF': '43', '4s': '4', '6s': '2', 'SR': '130.23', 'Pos': '7', 'Dismissal': 'bowled', 'Inns': '2', 'Opposition': 'v England', 'Ground': 'Kolkata', 'Start Date': '22 Jan 2017'}, 'ODI # 3878': {'Runs': '20*', 'Mins': '8', 'BF': '6', '4s': '0', '6s': '3', 'SR': '333.33', 'Pos': '5', 'Dismissal': 'not out', 'Inns': '1', 'Opposition': 'v Pakistan', 'Ground': 'Birmingham', 'Start Date': '4 Jun 2017'}, 'ODI # 3882': {'Runs': '9', 'Mins': '8', 'BF': '5', '4s': '0', '6s': '1', 'SR': '180.00', 'Pos': '6', 'Dismissal': 'caught', 'Inns': '1', 'Opposition': 'v Sri Lanka', 'Ground': 'The Oval', 'Start Date': '8 Jun 2017'}, 'ODI # 3886': {'Runs': 'DNB', 'Mins': '-', 'BF': '-', '4s': '-', '6s': '-', 'SR': '-', 'Pos': '-', 'Dismissal': '-', 'Inns': '2', 'Opposition': 'v South Africa', 'Ground': 'The Oval', 'Start Date': '11 Jun 2017'}, 'ODI # 3891': {'Runs': 'DNB', 'Mins': '-', 'BF': '-', '4s': '-', '6s': '-', 'SR': '-', 'Pos': '-', 'Dismissal': '-', 'Inns': '2', 'Opposition': 'v Bangladesh', 'Ground': 'Birmingham', 'Start Date': '15 Jun 2017'}, 'ODI # 3894': {'Runs': '76', 'Mins': '46', 'BF': '43', '4s': '4', '6s': '6', 'SR': '176.74', 'Pos': '7', 'Dismissal': 'run out', 'Inns': '2', 'Opposition': 'v Pakistan', 'Ground': 'The Oval', 'Start Date': '18 Jun 2017'}, 'ODI # 3895': {'Runs': 'DNB', 'Mins': '-', 'BF': '-', '4s': '-', '6s': '-', 'SR': '-', 'Pos': '-', 'Dismissal': '-', 'Inns': '1', 'Opposition': 'v West Indies', 'Ground': 'Port of Spain', 'Start Date': '23 Jun 2017'}, 'ODI # 3896': {'Runs': '4', 'Mins': '-', 'BF': '5', '4s': '0', '6s': '0', 'SR': '80.00', 'Pos': '4', 'Dismissal': 'caught', 'Inns': '1', 'Opposition': 'v West Indies', 'Ground': 'Port of Spain', 'Start Date': '25 Jun 2017'}, 'ODI # 3898': {'Runs': 'DNB', 'Mins': '-', 'BF': '-', '4s': '-', '6s': '-', 'SR': '-', 'Pos': '-', 'Dismissal': '-', 'Inns': '1', 'Opposition': 'v West Indies', 'Ground': 'North Sound', 'Start Date': '30 Jun 2017'}, 'ODI # 3900': {'Runs': '20', 'Mins': '-', 'BF': '21', '4s': '1', '6s': '1', 'SR': '95.23', 'Pos': '7', 'Dismissal': 'bowled', 'Inns': '2', 'Opposition': 'v West Indies', 'Ground': 'North Sound', 'Start Date': '2 Jul 2017'}, 'ODI # 3902': {'Runs': 'DNB', 'Mins': '-', 'BF': '-', '4s': '-', '6s': '-', 'SR': '-', 'Pos': '-', 'Dismissal': '-', 'Inns': '2', 'Opposition': 'v West Indies', 'Ground': 'Kingston', 'Start Date': '6 Jul 2017'}, 'ODI # 3905': {'Runs': 'DNB', 'Mins': '-', 'BF': '-', '4s': '-', '6s': '-', 'SR': '-', 'Pos': '-', 'Dismissal': '-', 'Inns': '2', 'Opposition': 'v Sri Lanka', 'Ground': 'Dambulla', 'Start Date': '20 Aug 2017'}, 'ODI # 3906': {'Runs': '0', 'Mins': '-', 'BF': '3', '4s': '0', '6s': '0', 'SR': '0.00', 'Pos': '7', 'Dismissal': 'stumped', 'Inns': '2', 'Opposition': 'v Sri Lanka', 'Ground': 'Pallekele', 'Start Date': '24 Aug 2017'}, 'ODI # 3907': {'Runs': 'DNB', 'Mins': '-', 'BF': '-', '4s': '-', '6s': '-', 'SR': '-', 'Pos': '-', 'Dismissal': '-', 'Inns': '2', 'Opposition': 'v Sri Lanka', 'Ground': 'Pallekele', 'Start Date': '27 Aug 2017'}, 'ODI # 3908': {'Runs': '19', 'Mins': '-', 'BF': '18', '4s': '1', '6s': '1', 'SR': '105.55', 'Pos': '4', 'Dismissal': 'caught', 'Inns': '1', 'Opposition': 'v Sri Lanka', 'Ground': 'Colombo (RPS)', 'Start Date': '31 Aug 2017'}, 'ODI # 3910': {'Runs': '83', 'Mins': '86', 'BF': '66', '4s': '5', '6s': '5', 'SR': '125.75', 'Pos': '7', 'Dismissal': 'caught', 'Inns': '1', 'Opposition': 'v Australia', 'Ground': 'Chennai', 'Start Date': '17 Sep 2017'}, 'ODI # 3912': {'Runs': '20', 'Mins': '56', 'BF': '26', '4s': '2', '6s': '0', 'SR': '76.92', 'Pos': '7', 'Dismissal': 'caught', 'Inns': '1', 'Opposition': 'v Australia', 'Ground': 'Kolkata', 'Start Date': '21 Sep 2017'}, 'ODI # 3914': {'Runs': '78', 'Mins': '98', 'BF': '72', '4s': '5', '6s': '4', 'SR': '108.33', 'Pos': '4', 'Dismissal': 'caught', 'Inns': '2', 'Opposition': 'v Australia', 'Ground': 'Indore', 'Start Date': '24 Sep 2017'}, 'ODI # 3917': {'Runs': '41', 'Mins': '64', 'BF': '40', '4s': '1', '6s': '3', 'SR': '102.50', 'Pos': '4', 'Dismissal': 'caught', 'Inns': '2', 'Opposition': 'v Australia', 'Ground': 'Bengaluru', 'Start Date': '28 Sep 2017'}, 'ODI # 3919': {'Runs': 'DNB', 'Mins': '-', 'BF': '-', '4s': '-', '6s': '-', 'SR': '-', 'Pos': '-', 'Dismissal': '-', 'Inns': '2', 'Opposition': 'v Australia', 'Ground': 'Nagpur', 'Start Date': '1 Oct 2017'}, 'ODI # 3928': {'Runs': '16', 'Mins': '18', 'BF': '16', '4s': '1', '6s': '1', 'SR': '100.00', 'Pos': '7', 'Dismissal': 'caught', 'Inns': '1', 'Opposition': 'v New Zealand', 'Ground': 'Mumbai', 'Start Date': '22 Oct 2017'}, 'ODI # 3931': {'Runs': '30', 'Mins': '48', 'BF': '31', '4s': '2', '6s': '1', 'SR': '96.77', 'Pos': '5', 'Dismissal': 'caught', 'Inns': '2', 'Opposition': 'v New Zealand', 'Ground': 'Pune', 'Start Date': '25 Oct 2017'}, 'ODI # 3932': {'Runs': '8', 'Mins': '9', 'BF': '6', '4s': '1', '6s': '0', 'SR': '133.33', 'Pos': '4', 'Dismissal': 'caught', 'Inns': '1', 'Opposition': 'v New Zealand', 'Ground': 'Kanpur', 'Start Date': '29 Oct 2017'}, 'ODI # 3939': {'Runs': '10', 'Mins': '11', 'BF': '10', '4s': '2', '6s': '0', 'SR': '100.00', 'Pos': '7', 'Dismissal': 'caught', 'Inns': '1', 'Opposition': 'v Sri Lanka', 'Ground': 'Dharamsala', 'Start Date': '10 Dec 2017'}, 'ODI # 3941': {'Runs': '8', 'Mins': '12', 'BF': '5', '4s': '1', '6s': '0', 'SR': '160.00', 'Pos': '5', 'Dismissal': 'caught', 'Inns': '1', 'Opposition': 'v Sri Lanka', 'Ground': 'Mohali', 'Start Date': '13 Dec 2017'}, 'ODI # 3942': {'Runs': 'DNB', 'Mins': '-', 'BF': '-', '4s': '-', '6s': '-', 'SR': '-', 'Pos': '-', 'Dismissal': '-', 'Inns': '2', 'Opposition': 'v Sri Lanka', 'Ground': 'Visakhapatnam', 'Start Date': '17 Dec 2017'}, 'ODI # 3969': {'Runs': '3*', 'Mins': '15', 'BF': '6', '4s': '0', '6s': '0', 'SR': '50.00', 'Pos': '5', 'Dismissal': 'not out', 'Inns': '2', 'Opposition': 'v South Africa', 'Ground': 'Durban', 'Start Date': '1 Feb 2018'}, 'ODI # 3970': {'Runs': 'DNB', 'Mins': '-', 'BF': '-', '4s': '-', '6s': '-', 'SR': '-', 'Pos': '-', 'Dismissal': '-', 'Inns': '2', 'Opposition': 'v South Africa', 'Ground': 'Centurion', 'Start Date': '4 Feb 2018'}, 'ODI # 3971': {'Runs': '14', 'Mins': '21', 'BF': '15', '4s': '0', '6s': '1', 'SR': '93.33', 'Pos': '5', 'Dismissal': 'caught', 'Inns': '1', 'Opposition': 'v South Africa', 'Ground': 'Cape Town', 'Start Date': '7 Feb 2018'}, 'ODI # 3973': {'Runs': '9', 'Mins': '17', 'BF': '13', '4s': '1', '6s': '0', 'SR': '69.23', 'Pos': '7', 'Dismissal': 'caught', 'Inns': '1', 'Opposition': 'v South Africa', 'Ground': 'Johannesburg', 'Start Date': '10 Feb 2018'}, 'ODI # 3976': {'Runs': '0', 'Mins': '1', 'BF': '1', '4s': '0', '6s': '0', 'SR': '0.00', 'Pos': '6', 'Dismissal': 'caught', 'Inns': '1', 'Opposition': 'v South Africa', 'Ground': 'Port Elizabeth', 'Start Date': '13 Feb 2018'}, 'ODI # 3978': {'Runs': 'DNB', 'Mins': '-', 'BF': '-', '4s': '-', '6s': '-', 'SR': '-', 'Pos': '-', 'Dismissal': '-', 'Inns': '2', 'Opposition': 'v South Africa', 'Ground': 'Centurion', 'Start Date': '16 Feb 2018'}, 'ODI # 4014': {'Runs': 'DNB', 'Mins': '-', 'BF': '-', '4s': '-', '6s': '-', 'SR': '-', 'Pos': '-', 'Dismissal': '-', 'Inns': '2', 'Opposition': 'v England', 'Ground': 'Nottingham', 'Start Date': '12 Jul 2018'}, 'ODI # 4016': {'Runs': '21', 'Mins': '-', 'BF': '22', '4s': '1', '6s': '0', 'SR': '95.45', 'Pos': '7', 'Dismissal': 'caught', 'Inns': '2', 'Opposition': 'v England', 'Ground': "Lord's", 'Start Date': '14 Jul 2018'}, 'ODI # 4018': {'Runs': '21', 'Mins': '29', 'BF': '21', '4s': '2', '6s': '0', 'SR': '100.00', 'Pos': '7', 'Dismissal': 'caught', 'Inns': '1', 'Opposition': 'v England', 'Ground': 'Leeds', 'Start Date': '17 Jul 2018'}, 'ODI # 4040': {'Runs': 'DNB', 'Mins': '-', 'BF': '-', '4s': '-', '6s': '-', 'SR': '-', 'Pos': '-', 'Dismissal': '-', 'Inns': '2', 'Opposition': 'v Pakistan', 'Ground': 'Dubai (DSC)', 'Start Date': '19 Sep 2018'}, 'ODI # 4088': {'Runs': 'DNB', 'Mins': '-', 'BF': '-', '4s': '-', '6s': '-', 'SR': '-', 'Pos': '-', 'Dismissal': '-', 'Inns': '2', 'Opposition': 'v New Zealand', 'Ground': 'Mount Maunganui', 'Start Date': '28 Jan 2019'}, 'ODI # 4091': {'Runs': '16', 'Mins': '37', 'BF': '20', '4s': '4', '6s': '0', 'SR': '80.00', 'Pos': '7', 'Dismissal': 'caught', 'Inns': '1', 'Opposition': 'v New Zealand', 'Ground': 'Hamilton', 'Start Date': '31 Jan 2019'}, 'ODI # 4092': {'Runs': '45', 'Mins': '27', 'BF': '22', '4s': '2', '6s': '5', 'SR': '204.54', 'Pos': '8', 'Dismissal': 'caught', 'Inns': '1', 'Opposition': 'v New Zealand', 'Ground': 'Wellington', 'Start Date': '3 Feb 2019'}, 'ODI # 4150': {'Runs': '15*', 'Mins': '8', 'BF': '7', '4s': '3', '6s': '0', 'SR': '214.28', 'Pos': '6', 'Dismissal': 'not out', 'Inns': '2', 'Opposition': 'v South Africa', 'Ground': 'Southampton', 'Start Date': '5 Jun 2019'}, 'ODI # 4155': {'Runs': '48', 'Mins': '41', 'BF': '27', '4s': '4', '6s': '3', 'SR': '177.77', 'Pos': '4', 'Dismissal': 'caught', 'Inns': '1', 'Opposition': 'v Australia', 'Ground': 'The Oval', 'Start Date': '9 Jun 2019'}, 'ODI # 4161': {'Runs': '26', 'Mins': '24', 'BF': '19', '4s': '2', '6s': '1', 'SR': '136.84', 'Pos': '4', 'Dismissal': 'caught', 'Inns': '1', 'Opposition': 'v Pakistan', 'Ground': 'Manchester', 'Start Date': '16 Jun 2019'}, 'ODI # 4169': {'Runs': '7', 'Mins': '23', 'BF': '9', '4s': '0', '6s': '0', 'SR': '77.77', 'Pos': '7', 'Dismissal': 'caught', 'Inns': '1', 'Opposition': 'v Afghanistan', 'Ground': 'Southampton', 'Start Date': '22 Jun 2019'}, 'ODI # 4175': {'Runs': '46', 'Mins': '48', 'BF': '38', '4s': '5', '6s': '0', 'SR': '121.05', 'Pos': '7', 'Dismissal': 'caught', 'Inns': '1', 'Opposition': 'v West Indies', 'Ground': 'Manchester', 'Start Date': '27 Jun 2019'}, 'ODI # 4179': {'Runs': '45', 'Mins': '49', 'BF': '33', '4s': '4', '6s': '0', 'SR': '136.36', 'Pos': '5', 'Dismissal': 'caught', 'Inns': '2', 'Opposition': 'v England', 'Ground': 'Birmingham', 'Start Date': '30 Jun 2019'}, 'ODI # 4182': {'Runs': '0', 'Mins': '4', 'BF': '2', '4s': '0', '6s': '0', 'SR': '0.00', 'Pos': '5', 'Dismissal': 'caught', 'Inns': '1', 'Opposition': 'v Bangladesh', 'Ground': 'Birmingham', 'Start Date': '2 Jul 2019'}, 'ODI # 4187': {'Runs': '7*', 'Mins': '8', 'BF': '4', '4s': '1', '6s': '0', 'SR': '175.00', 'Pos': '5', 'Dismissal': 'not out', 'Inns': '2', 'Opposition': 'v Sri Lanka', 'Ground': 'Leeds', 'Start Date': '6 Jul 2019'}, 'ODI # 4190': {'Runs': '32', 'Mins': '81', 'BF': '62', '4s': '2', '6s': '0', 'SR': '51.61', 'Pos': '6', 'Dismissal': 'caught', 'Inns': '2', 'Opposition': 'v New Zealand', 'Ground': 'Manchester', 'Start Date': '9 Jul 2019'}}

In [149]:
player_2 =  pd.DataFrame.from_dict(player2_dict,"index")

In [150]:
from enum import Enum
class Formats(Enum):
    Tests = "Tests"
    ODIs = "ODIs"
    T20Is = "T20Is"

In [151]:
player_2

,Runs,Mins,BF,4s,6s,SR,Pos,Dismissal,Inns,Opposition,Ground,Start Date
ODI # 3796,DNB,-,-,-,-,-,-,-,2,v New Zealand,Dharamsala,16 Oct 2016
ODI # 3797,36,51,32,3,0,112.50,8,caught,2,v New Zealand,Delhi,20 Oct 2016
ODI # 3798,DNB,-,-,-,-,-,-,-,2,v New Zealand,Mohali,23 Oct 2016
ODI # 3799,9,18,13,0,0,69.23,8,caught,2,v New Zealand,Ranchi,26 Oct 2016
ODI # 3819,40*,60,37,3,1,108.10,7,not out,2,v England,Pune,15 Jan 2017
ODI # 3821,19*,23,9,2,1,211.11,7,not out,1,v England,Cuttack,19 Jan 2017
ODI # 3824,56,67,43,4,2,130.23,7,bowled,2,v England,Kolkata,22 Jan 2017
ODI # 3878,20*,8,6,0,3,333.33,5,not out,1,v Pakistan,Birmingham,4 Jun 2017
ODI # 3882,9,8,5,0,1,180.00,6,caught,1,v Sri Lanka,The Oval,8 Jun 2017
ODI # 3886,DNB,-,-,-,-,-,-,-,2,v South Africa,The Oval,11 Jun 2017
ODI # 3891,DNB,-,-,-,-,-,-,-,2,v Bangladesh,Birmingham,15 Jun 2017
ODI # 3894,76,46,43,4,6,176.74,7,run out,2,v Pakistan,The Oval,18 Jun 2017
ODI # 3895,DNB,-,-,-,-,-,-,-,1,v West Indies,Port of Spain,23 Jun 2017
ODI # 3896,4,-,5,0,0,80.00,4,caught,1,v West Indies,Port of Spain,25 Jun 2017
ODI # 3898,DNB,-,-,-,-,-,-,-,1,v West Indies,North Sound,30 Jun 2017
ODI # 3900,20,-,21,1,1,95.23,7,bowled,2,v West Indies,North Sound,2 Jul 2017
ODI # 3902,DNB,-,-,-,-,-,-,-,2,v West Indies,Kingston,6 Jul 2017
ODI # 3905,DNB,-,-,-,-,-,-,-,2,v Sri Lanka,Dambulla,20 Aug 2017
ODI # 3906,0,-,3,0,0,0.00,7,stumped,2,v Sri Lanka,Pallekele,24 Aug 2017
ODI # 3907,DNB,-,-,-,-,-,-,-,2,v Sri Lanka,Pallekele,27 Aug 2017
ODI # 3908,19,-,18,1,1,105.55,4,caught,1,v Sri Lanka,Colombo (RPS),31 Aug 2017
ODI # 3910,83,86,66,5,5,125.75,7,caught,1,v Australia,Chennai,17 Sep 2017
ODI # 3912,20,56,26,2,0,76.92,7,caught,1,v Australia,Kolkata,21 Sep 2017
ODI # 3914,78,98,72,5,4,108.33,4,caught,2,v Australia,Indore,24 Sep 2017
ODI # 3917,41,64,40,1,3,102.50,4,caught,2,v Australia,Bengaluru,28 Sep 2017
ODI # 3919,DNB,-,-,-,-,-,-,-,2,v Australia,Nagpur,1 Oct 2017
ODI # 3928,16,18,16,1,1,100.00,7,caught,1,v New Zealand,Mumbai,22 Oct 2017
ODI # 3931,30,48,31,2,1,96.77,5,caught,2,v New Zealand,Pune,25 Oct 2017
ODI # 3932,8,9,6,1,0,133.33,4,caught,1,v New Zealand,Kanpur,29 Oct 2017
ODI # 3939,10,11,10,2,0,100.00,7,caught,1,v Sri Lanka,Dharamsala,10 Dec 2017
ODI # 3941,8,12,5,1,0,160.00,5,caught,1,v Sri Lanka,Mohali,13 Dec 2017
ODI # 3942,DNB,-,-,-,-,-,-,-,2,v Sri Lanka,Visakhapatnam,17 Dec 2017
ODI # 3969,3*,15,6,0,0,50.00,5,not out,2,v South Africa,Durban,1 Feb 2018
ODI # 3970,DNB,-,-,-,-,-,-,-,2,v South Africa,Centurion,4 Feb 2018
ODI # 3971,14,21,15,0,1,93.33,5,caught,1,v South Africa,Cape Town,7 Feb 2018
ODI # 3973,9,17,13,1,0,69.23,7,caught,1,v South Africa,Johannesburg,10 Feb 2018
ODI # 3976,0,1,1,0,0,0.00,6,caught,1,v South Africa,Port Elizabeth,13 Feb 2018
ODI # 3978,DNB,-,-,-,-,-,-,-,2,v South Africa,Centurion,16 Feb 2018
ODI # 4014,DNB,-,-,-,-,-,-,-,2,v England,Nottingham,12 Jul 2018
ODI # 4016,21,-,22,1,0,95.45,7,caught,2,v England,Lord's,14 Jul 2018
ODI # 4018,21,29,21,2,0,100.00,7,caught,1,v England,Leeds,17 Jul 2018
ODI # 4040,DNB,-,-,-,-,-,-,-,2,v Pakistan,Dubai (DSC),19 Sep 2018
ODI # 4088,DNB,-,-,-,-,-,-,-,2,v New Zealand,Mount Maunganui,28 Jan 2019
ODI # 4091,16,37,20,4,0,80.00,7,caught,1,v New Zealand,Hamilton,31 Jan 2019
ODI # 4092,45,27,22,2,5,204.54,8,caught,1,v New Zealand,Wellington,3 Feb 2019
ODI # 4150,15*,8,7,3,0,214.28,6,not out,2,v South Africa,Southampton,5 Jun 2019
ODI # 4155,48,41,27,4,3,177.77,4,caught,1,v Australia,The Oval,9 Jun 2019
ODI # 4161,26,24,19,2,1,136.84,4,caught,1,v Pakistan,Manchester,16 Jun 2019
ODI # 4169,7,23,9,0,0,77.77,7,caught,1,v Afghanistan,Southampton,22 Jun 2019
ODI # 4175,46,48,38,5,0,121.05,7,caught,1,v West Indies,Manchester,27 Jun 2019
ODI # 4179,45,49,33,4,0,136.36,5,caught,2,v England,Birmingham,30 Jun 2019
ODI # 4182,0,4,2,0,0,0.00,5,caught,1,v Bangladesh,Birmingham,2 Jul 2019
ODI # 4187,7*,8,4,1,0,175.00,5,not out,2,v Sri Lanka,Leeds,6 Jul 2019
ODI # 4190,32,81,62,2,0,51.61,6,caught,2,v New Zealand,Manchester,9 Jul 2019

In [152]:
summary_df = player_2.groupby(['Opposition']).agg({'Runs': 'sum', 'Opposition': 'count'})

In [153]:
summary_df.rename(columns={"Opposition":"Matches"},inplace=True)

In [154]:
summary_df

                                   Runs  Matches
Opposition
v Afghanistan                         7        1
v Australia               83207841DNB48        6
v Bangladesh                       DNB0        2
v England             40*19*56DNB212145        7
v New Zealand   DNB36DNB916308DNB164532       11
v Pakistan                   20*76DNB26        4
v South Africa       DNB3*DNB1490DNB15*        8
v Sri Lanka          9DNB0DNB19108DNB7*        9
v West Indies            DNB4DNB20DNB46        6

In [155]:
summary_df.reset_index(inplace=True)

In [156]:
summary_df

       Opposition                     Runs  Matches
0   v Afghanistan                        7        1
1     v Australia            83207841DNB48        6
2    v Bangladesh                     DNB0        2
3       v England        40*19*56DNB212145        7
4   v New Zealand  DNB36DNB916308DNB164532       11
5      v Pakistan               20*76DNB26        4
6  v South Africa       DNB3*DNB1490DNB15*        8
7     v Sri Lanka       9DNB0DNB19108DNB7*        9
8   v West Indies           DNB4DNB20DNB46        6

In [157]:
def format_country(country):
    country = country.split("v")[1]
    return country

In [158]:
player_2["Opposition"] = player_2["Opposition"].apply(lambda x: format_country(x) )

In [159]:
summary_df

       Opposition                     Runs  Matches
0   v Afghanistan                        7        1
1     v Australia            83207841DNB48        6
2    v Bangladesh                     DNB0        2
3       v England        40*19*56DNB212145        7
4   v New Zealand  DNB36DNB916308DNB164532       11
5      v Pakistan               20*76DNB26        4
6  v South Africa       DNB3*DNB1490DNB15*        8
7     v Sri Lanka       9DNB0DNB19108DNB7*        9
8   v West Indies           DNB4DNB20DNB46        6

In [160]:
summary = player_2.groupby(['Opposition'])

In [161]:
def calculate_average(data_frame):
    print(data_frame)
    total_runs = 0
    matches = 0
    for index, row in data_frame.iterrows():
        current_row_run = row['Runs']
        if '*' in current_row_run:
            run = current_row_run.replace("*",'')
            total_runs = total_runs + int(run)
        else:
            matches+=1
            total_runs = total_runs + int(current_row_run)
    print(total_runs)        
    return round((total_runs/matches),2)

In [162]:
averages = []
for key, item in summary:
     averages.append(calculate_average(summary.get_group(key)))

           Runs Mins BF 4s 6s     SR Pos Dismissal Inns    Opposition  \
ODI # 4169    7   23  9  0  0  77.77   7    caught    1   Afghanistan

                 Ground   Start Date
ODI # 4169  Southampton  22 Jun 2019
7
           Runs Mins  BF 4s 6s      SR Pos Dismissal Inns  Opposition  \
ODI # 3910   83   86  66  5  5  125.75   7    caught    1   Australia
ODI # 3912   20   56  26  2  0   76.92   7    caught    1   Australia
ODI # 3914   78   98  72  5  4  108.33   4    caught    2   Australia
ODI # 3917   41   64  40  1  3  102.50   4    caught    2   Australia
ODI # 3919  DNB    -   -  -  -       -   -         -    2   Australia
ODI # 4155   48   41  27  4  3  177.77   4    caught    1   Australia

               Ground   Start Date
ODI # 3910    Chennai  17 Sep 2017
ODI # 3912    Kolkata  21 Sep 2017
ODI # 3914     Indore  24 Sep 2017
ODI # 3917  Bengaluru  28 Sep 2017
ODI # 3919     Nagpur   1 Oct 2017
ODI # 4155   The Oval   9 Jun 2019

ValueError: invalid literal for int() with base 10: 'DNB'

In [ ]:
data_frame["Runs"] = player_2["Runs"].apply(lambda runs: formatRuns(runs))
summary_df = data_frame.groupby(['Opposition']).agg({'Runs': 'sum', 'Opposition': 'count'})

In [ ]:
rr=pd.Series(averages)
rr

In [ ]:
summary_df["Average"] = rr.values

In [ ]:
seri = pd.Series(["AFG","AUS","BGD","GBR","NZL","PAK","ZAF","LKA","USA"])

In [ ]:
summary_df['Code'] = seri.values

In [ ]:
summary_df

In [ ]:
import plotly.graph_objects as go
import pandas as pd

fig = go.Figure(data=go.Choropleth(
    locations = summary_df['Code'],
    z = summary_df['Runs'],
    text = summary_df['Opposition'],
    colorscale = 'Blues',
    autocolorscale=False,
    reversescale=True,
    marker_line_color='darkgray',
    marker_line_width=0.5,
    colorbar_tickprefix = '$',
    colorbar_title = 'GDP<br>Billions US$',
))

fig.update_layout(
    title_text='2014 Global GDP',
    geo=dict(
        showframe=False,
        showcoastlines=False,
        projection_type='equirectangular'
    ),
    annotations = [dict(
        x=0.55,
        y=0.1,
        xref='paper',
        yref='paper',
        text='Source: <a href="https://www.cia.gov/library/publications/the-world-factbook/fields/2195.html">\
            CIA World Factbook</a>',
        showarrow = False
    )]
)

fig.show()